// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'space_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String EARTH = 'assets/images/scroll_images/earth.png';
  static const String JUPITER = 'assets/images/scroll_images/jupiter.png';
  static const String MARS = 'assets/images/scroll_images/mars.png';
  static const String MERCURY = 'assets/images/scroll_images/mercury.png';
  static const String NEPTUNE = 'assets/images/scroll_images/neptune.png';
  static const String SATURN = 'assets/images/scroll_images/saturn.png';
  static const String SUN = 'assets/images/scroll_images/sun.png';
  static const String URANUS = 'assets/images/scroll_images/uranus.png';
  static const String VENUS = 'assets/images/scroll_images/venus.png';
  static const String TOP = 'assets/images/top.png';
}
